[ko] fixed typos and apply updates in English doc
scala/docs.scala-lang pull request #1746
Opened 2020-08-01 15:37 UTC by chipmunklimo

trying to keep updating for Korean docs 😅

2020-08-01 17:24 UTC, eed3si9n commented
@scala/docs-ko review please?

2020-09-01 18:26 UTC, SethTisue commented
@chipmunklimo do you know anyone who could review this?

2020-09-01 22:12 UTC, eugene70 commented
I will review this ASAP.

2020-09-11 01:41 UTC, eugene70 requested changes
I have commented on several. Please consider it.

2020-09-11 01:41 UTC, eugene70 commented on _ko/tour/implicit-conversions.md
> +암시적 메서드 `Int => Ordered[Int]`는 `scala.Predef.intWrapper`를 통해 자동으로 제공된다. 암시적 메서드 `Int => Ordered[Int]`의 예시는 아래와 같다.
`scala.Predef.intWrapper`는 암시적 메서드 `Int => Ordered[Int]`를 자동으로 제공한다. 다음은 암시적 메서드 `Int => Ordered[Int]`의 예시이다.

2020-09-11 01:41 UTC, eugene70 commented on _ko/tour/implicit-conversions.md
> +암시적으로 임포트되는 객체 `scala.Predef`는 자주 사용되는 타입들의 몇몇 별칭(예: 별칭이 `Map`인 `scala.collection.immutable.Map`)과 메소드(예: `assert`), 그리고 여러 암시적 변환을 선언한다.
암시적으로 임포트되는 객체 `scala.Predef`는 자주 사용하는 타입의 별칭(예: `scala.collection.immutable.Map`의 별칭 `Map` )과 메소드(예: `assert`), 그리고 여러 암시적 변환을 선언한다.

2020-09-11 01:41 UTC, eugene70 commented on _ko/tour/implicit-conversions.md
> +* 암시적 변환의 정의가 있는 범위로 `scala.language.implicitConversions` 임포트
* 암시적 변환의 정의가 있는 범위 내에서 `scala.language.implicitConversions`를 임포트

2020-09-11 01:41 UTC, eugene70 commented on _ko/tour/implicit-conversions.md
> +컴파일러가 변환을 적용하면 경고가 발생하지 않는다.
컴파일러가 변환을 적용할 때에는 경고가 발생하지 않는다.

2020-09-30 16:44 UTC, chipmunklimo commented
sorry I'm late😅 wil update soon

2020-10-03 12:46 UTC, chipmunklimo commented
@eugene70 could you help review this again please? I updated😁

2020-10-03 13:33 UTC, eugene70 approved these changes
LGTM

2020-10-05 14:59 UTC, chipmunklimo commented
@eed3si9n @SethTisue good day! please help merge🤗

2020-10-05 15:36 UTC, som-snytt commented
So glad Hacktoberfest doesn't come in August in Korea.

2020-10-05 15:37 UTC, merged

2020-10-05 16:50 UTC, SethTisue commented
thanks everybody :-)