Translate untranslated chapters to Polish
scala/docs.scala-lang pull request #1760
Opened 2020-08-26 20:31 UTC by Unrooted

This translates the untranslated chapter of the Tour of Scala into Polish.

2020-08-26 22:57 UTC, eed3si9n commented
Thanks for the contribution! I can't review this myself so could you find someone who can? Fortunately Poland has no shortage of knowledgable Scala programmers so I'm sure you can find someone in no time. /cc @Krever, @romanowski, @rkrzewski, @EncodePanda

2020-08-27 06:02 UTC, Unrooted commented
I added f6e4b5051b1fb8ac7d0a9a390bb92d8b40fb7fc4 to the #1758 a few days ago and it's also added in here, I guess we can close #1758 and focus on this PR since it also does include the same thing but doesn't have such a mess in logs.

2020-08-27 08:01 UTC, Krever requested changes
Few changes, but looks good in general, thanks! 
I haven't checked the new pages ordering though, I hope its alright.

2020-08-29 15:09 UTC, Krever approved these changes
LGTM. Would be good if one more person could look at it, but if not should still be ok.

2020-08-29 20:32 UTC, rkrzewski reviewed
Hey, I've added some edit suggestions for the consideration of translation's author.

2020-08-29 20:32 UTC, rkrzewski commented on _pl/tour/by-name-parameters.md
> +_Parametry przekazywane według nazwy_ są ewaluowane za każdym razem gdy są używane. Nie zostaną w ogóle wyewaluowane jeśli nie będą używane. Jest to podobne do zastępowania parametrów według nazwy pr
```suggestion
_Parametry przekazywane według nazwy_ są ewaluowane za każdym razem gdy są używane. Nie zostaną w ogóle wyewaluowane jeśli nie będą używane. Jest to podobne do zastępowania parametrów w ciele funkcji wyrażeniami podanymi w miejscu jej wywołania. Są przeciwieństwem do _parametrów przekazywanych według wartości_. Aby utworzyć parametr przekazywany według nazwy, po prostu dodaj `=>` przed jego typem.
```

2020-08-29 20:32 UTC, rkrzewski commented on _pl/tour/by-name-parameters.md
> +Teraz, kiedy przekażemy `i>0` jako nasz `condition` (warunek) i `println(i); i-= 1` jako `body`, nasze wyrażenie zachowuje się jak standardowa pętla while w wielu językach.
```suggestion
Jeśli przekażemy `i>0` jako nasz `condition` (warunek) i `println(i); i-= 1` jako `body`, nasze wyrażenie zachowuje się jak standardowa pętla while w wielu językach.
```

2020-08-29 20:32 UTC, rkrzewski commented on _pl/tour/by-name-parameters.md
> +Ta możliwość opóźnienia ewaluacji parametru do czasu jego użycia może zwiększyć wydajność, jeśli ewaluacja parametru wymaga intensywnych obliczeń lub dłużej działającego bloku kodu, takiego jak pobie
```suggestion
Ta możliwość opóźnienia ewaluacji parametru do czasu jego użycia może zwiększyć wydajność, jeśli ewaluacja parametru wymaga intensywnych obliczeń lub dłużej działającego bloku kodu, takiego jak pobieranie treści spod adresu URL.
```

2020-08-29 20:32 UTC, rkrzewski commented on _pl/tour/package-objects.md
> +Obiekty pakietu mogą zawierać dowolne definicje, nie tylko definicje zmiennych i metod. Na przykład, są często używane do przechowywania aliasów typów dla całego pakietu i niejawnych konwersji. Obiek
```suggestion
Obiekty pakietu mogą zawierać dowolne definicje, nie tylko definicje zmiennych i metod. Na przykład, są często używane do przechowywania aliasów typów i niejawnych konwersji. Obiekty pakietu mogą nawet dziedziczyć klasy i cechy (traits) Scali.
```

2020-08-29 20:32 UTC, rkrzewski commented on _pl/tour/package-objects.md
> +Z założenia, kod źródłowy obiektu pakietu jest zwykle umieszczany w pliku źródłowym o nazwie `package.scala`.
```suggestion
Zgodnie z konwencją, kod źródłowy obiektu pakietu jest zwykle umieszczany w pliku źródłowym o nazwie `package.scala`.
```

2020-08-29 20:32 UTC, rkrzewski commented on _pl/tour/package-objects.md
> +Oto jak to się robi:
```suggestion
Możesz zrobić to w następujący sposób:
```

2020-08-29 20:32 UTC, rkrzewski commented on _pl/tour/package-objects.md
> +Jako przykład tego, jak wygląda użytkowanie, obiekt `PrintPlanted` importuje `planted` i `showFruit` w ten sam sposób, w jaki importuje klasę `Fruit` - używając importu wieloznacznego w pakiecie `gar
```suggestion
Jako przykład tego, jak wygląda użycie definicji przygotowanych w ten sposób, obiekt `PrintPlanted` importuje `planted` i `showFruit` w ten sam sposób, w jaki importuje klasę `Fruit` - używając importu wieloznacznego w pakiecie `gardening.fruits`.
```

2020-08-29 20:32 UTC, rkrzewski commented on _pl/tour/packages-and-imports.md
> +Deklaracje `import` służą do uzyskiwania dostępu do członków (members, tzn.: klasy, cechy, funkcje itp.) w innych pakietach. Aby uzyskać dostęp do członków tego samego pakietu, nie jest wymagana dekl
```suggestion
Deklaracje `import` służą do uzyskiwania dostępu do elementów składowych (members, tzn.: klasy, cechy, funkcje itp.) w innych pakietach. Aby uzyskać dostęp do elementów tego samego pakietu, nie jest wymagana deklaracja `import`. Deklaracje `import` są selektywne.
```

2020-08-29 20:32 UTC, rkrzewski commented on _pl/tour/packages-and-imports.md
> +import users.{User, UserPreferences}  // zaimportuj tylko wybranych członków
```suggestion
import users.{User, UserPreferences}  // zaimportuj tylko wybrane elementy
```

2020-08-29 20:32 UTC, rkrzewski commented on _pl/tour/packages-and-imports.md
> +Jedną z różnic w Scali od Javy jest to, że `import` można używać wszędzie:
```suggestion
Jedną z różnic w Scali od Javy jest to, że deklarację `import` można umieścić w dowolnym miejscu:
```

2020-08-29 20:32 UTC, rkrzewski commented on _pl/tour/packages-and-imports.md
> +W przypadku konfliktu nazw i konieczności zaimportowania czegoś z katalogu głównego projektu, poprzedź nazwę pakietu przedrostkiem `_root_`:
```suggestion
W przypadku konfliktu nazw i konieczności podania pełnej ścieżki w hierarchii nazw pakietów, poprzedź nazwę pakietu przedrostkiem `_root_`:
```

2020-08-29 20:32 UTC, rkrzewski commented on _pl/cheatsheets/index.md
> +<table>
Markdown code was replaced by HTML here. Was that intended?

2020-08-30 07:43 UTC, Unrooted commented
Yes, it was intended. I did it to make it consistent with the English version of the cheat sheet.

2020-09-01 18:36 UTC, SethTisue commented
Is this ready for merge?

2020-09-01 18:51 UTC, Unrooted commented
Yes, it is. I added all requested changes, it is ready for merge.

2020-09-01 18:52 UTC, merged

2020-09-01 18:53 UTC, SethTisue commented
thank you, @Unrooted and reviewers, for this substantial contribution!