Rework Scala 3 syntax rewriting doc in the migration guide
scala/docs.scala-lang pull request #2106
Opened 2021-06-30 13:15 UTC by adpi2

- Give a bit more detail about the new syntax.
- Make it clear that one must use the new control structure before rewriting to the indentation based syntax. Fix https://github.com/scalacenter/scala-3-migration-guide/issues/209
- Show the example in the correct order.
- Shorten the example to improve readability.

2021-07-12 12:54 UTC, adpi2 commented
@sjrd could you review this PR?

2021-08-03 16:50 UTC, SethTisue commented
@sjrd ping

2021-08-05 08:23 UTC, sjrd requested changes

2021-08-05 08:23 UTC, sjrd commented on _overviews/scala3-migration/tooling-syntax-rewriting.md
> +Scala 3 extends the syntax of the Scala language with the new control syntax and the significant indentation syntax.
```suggestion
Scala 3 extends the syntax of the Scala language with the new control structures syntax and the significant indentation syntax.
```

2021-08-05 08:23 UTC, sjrd commented on _overviews/scala3-migration/tooling-syntax-rewriting.md
> +In this chapter we show how you can use the compiler to rewrite your code automatically from the classic Scala 2 style to the new style or backward.
```suggestion
In this chapter we show how you can use the compiler to rewrite your code automatically from the classic Scala 2 style to the new style, or conversely.
```

2021-08-05 08:23 UTC, sjrd commented on _overviews/scala3-migration/tooling-syntax-rewriting.md
> +Notice that the parentheses around the `n == maxValue` disappeared, as well as the braces around the `i <- minValue to maxValue` and `j <- 0 to n` enumerators.
```suggestion
Notice that the parentheses around the `n == maxValue` disappeared, as well as the braces around the `i <- minValue to maxValue` and `j <- 0 to n` generators.
```

2021-08-05 08:23 UTC, sjrd commented on _overviews/scala3-migration/tooling-syntax-rewriting.md
> +We can observe that the number of lines was reduced by 2 thanks to the elimination of the closing curly braces.
This reads as *divided by 2*, which is clearly not true. Consider removing that sentence. IMO it doesn't bring any value.

2021-08-10 08:19 UTC, sjrd approved these changes

2021-08-10 08:20 UTC, merged