Grammar and Cleanup in Scala 3 Macro Documentation
scala/docs.scala-lang pull request #2121
Opened 2021-07-12 21:05 UTC by Zeimyth

I was trying to familiarize myself with Scala 3 macros today and found multiple issues in the documentation that I felt I could quickly clean up. There are other bigger issues and missing sections, but I tried to limit myself to just cleaning up the grammar of what was already there.

I made a few code snippet changes as well. For these, I usually tried to make things more consistent without trying to reinvent the code in question.

2021-08-02 16:04 UTC, Zeimyth commented
This has merge conflicts now. It's been open for 3 weeks with no activity. If this repo isn't interested in merging small grammar-correcting PRs in a timely manner, I'm of a mind to just close it.

2021-08-03 08:27 UTC, nicolasstucki requested changes
Looks great. Just needs some minor tweaks and a rebase.

2021-08-03 08:27 UTC, nicolasstucki commented on _overviews/scala3-macros/best-practices.md
> +'{ StringContext(${Varargs(x.parts.map(Expr(_)))}: _*) }
Maybe we should define the `StringContext` as `sc`

```scala
val sc: StringContext = ...
'{ StringContext(${Varargs(sc.parts.map(Expr(_)))}: _*) }
```

2021-08-03 08:27 UTC, nicolasstucki commented on _overviews/scala3-macros/tutorial/quotes.md
> +Due to some technical considerations, only non-quoted splices are allowed directly within `inline` definitions that we call a [macro][macros].
```suggestion
Due to some technical considerations, only top-level splices are allowed directly within `inline` definitions that we call a [macro][macros].
```

2021-08-03 08:27 UTC, nicolasstucki commented on _overviews/scala3-macros/tutorial/quotes.md
> +* When a type is abstract and it is used at a level that is deeper than the current level.
```suggestion
* When a type is abstract and it is used at a level that is higher than the current level.
```

2021-08-03 08:27 UTC, nicolasstucki commented on _overviews/scala3-macros/tutorial/quotes.md
> +This time, the pattern `Some($x: T)` will only match if the type of the Option is `Some[T]`.
```suggestion
This time, the pattern `Some($x: T)` will only match if the type of the `Option` is `Some[T]`.
```

2021-08-03 17:56 UTC, Zeimyth commented
Thanks for the extra recommended tweaks! Everything has been updated now.

2021-08-05 08:47 UTC, nicolasstucki approved these changes

2021-08-05 08:47 UTC, merged