add fr tour default parameter values
scala/docs.scala-lang pull request #2248
Opened 2021-12-02 16:06 UTC by apointeau

2022-01-05 15:09 UTC, julienrf requested changes

2022-01-05 15:09 UTC, julienrf commented on _fr/tour/default-parameter-values.md
> +Le paramètre `level` a une valeur par défaut, donc il est optionnel. Sur la dernière ligne, l'argument `"WARNING"` écrase la valeur par défaut `"INFO"`. Là où vous pourriez "overload" les méthodes en
```suggestion
Le paramètre `level` a une valeur par défaut, donc il est optionnel. Sur la dernière ligne, l'argument `"WARNING"` écrase la valeur par défaut `"INFO"`. Là où vous pourriez surcharger les méthodes en Java, vous pouvez simplement utiliser les paramètres optionnels pour obtenir le même effet. Cependant, lorsque l'appel omet un argument, tous les arguments suivants doivent être nommés.
```

2022-01-05 15:09 UTC, julienrf commented on _fr/tour/default-parameter-values.md
> +Ici nous pouvons dire que `y = 1`.
```suggestion
Ici nous devons écrire `y = 1` car nous omettons l’argument `x`.
```

2022-03-11 17:53 UTC, SethTisue commented
@apointeau care to respond to the review feedback?

2023-03-13 08:15 UTC, julienrf commented
Closing for inactivity. Please re-open it if you want to continue this work.

2023-03-13 08:15 UTC, closed without merging