Trad fr/extractor objects
scala/docs.scala-lang pull request #2268
Opened 2021-12-07 17:31 UTC by apointeau

2022-01-21 09:08 UTC, sjrd requested changes
Thanks for the PR. Sorry it took so long for someone to have a look at it.

2022-01-21 09:08 UTC, sjrd commented on _fr/tour/extractor-objects.md
> +Un objet extracteur est un objet avec une méthode `unapply`. Tandis que la méthode `apply` ressemble à un constructeur qui prend des arguments et crée un objet, `unapply` prend un object et essaye de
```suggestion
Un objet extracteur est un objet avec une méthode `unapply`. Tandis que la méthode `apply` ressemble à un constructeur qui prend des arguments et crée un objet, `unapply` prend un object et essaye de retourner ses arguments. Il est utilisé le plus souvent en filtrage par motif (*pattern matching*) ou avec les fonctions partielles.
```
I did not know the French term "filtrage par motif". I always use "pattern matching" even when I speak in French. I wouldn't be surprised if I'm not alone. So I suggest to at least once write the English name.

2022-01-21 09:08 UTC, sjrd commented on _fr/tour/extractor-objects.md
> +* Si c'est juste un test, retourner un `Boolean`. Pour l'instance `case even()`.
```suggestion
* Si c'est juste un test, retourner un `Boolean`. Par exemple, `case even()`.
```

2022-01-21 09:08 UTC, sjrd commented on _fr/tour/extractor-objects.md
> +Parfois, le nombre de valeurs à extraire n'est pas fixe et on souhaiterait retourner un nombre arbitraire de valeurs, en fonction des données d'entrée. Pour ce cas, vous pouvez définir des extracteur
```suggestion
Parfois, le nombre de valeurs à extraire n'est pas fixe et on souhaiterait retourner un nombre arbitraire de valeurs, en fonction des données d'entrée. Pour ce cas, vous pouvez définir des extracteurs avec la méthode `unapplySeq` qui retourne un `Option[Seq[T]]`. Un exemple commun d'utilisation est la déconstruction d'une liste en utilisant `case List(x, y, z) =>`. Un autre est la décomposition d'une `String` en utilisant une expression régulière `Regex`, comme `case r(name, remainingFields @ _*) =>`.
```

2022-03-11 17:53 UTC, SethTisue commented
@apointeau care to respond to the review feedback?

2022-03-18 13:22 UTC, apointeau commented
> @apointeau care to respond to the review feedback?

Good to me, thank you @sjrd

2022-03-21 10:50 UTC, sjrd approved these changes

2022-03-21 12:47 UTC, SethTisue commented
No policy. I often squash, but sometimes regular-merge if the commits seem history-conscious.

2022-03-21 13:04 UTC, merged