Move “Online Courses” documentation to a dedicated page
scala/docs.scala-lang pull request #2287
Opened 2022-01-05 15:54 UTC by julienrf

The documentation about the Scala Center’s MOOCs was mixed with other online resources, in https://docs.scala-lang.org/learn.html:

![Screenshot 2022-01-05 at 16-42-42 Online Resources](https://user-images.githubusercontent.com/332812/148246219-5d7b828e-039e-4fb5-8f42-878976a4d136.png)

We moved it to a new page at https://docs.scala-lang.org/online-courses.html:

![Screenshot 2022-01-05 at 16-32-53 Online Courses from The Scala Center](https://user-images.githubusercontent.com/332812/148246337-acc39737-e468-4267-940d-9870c34d298e.png)

Note that the new page uses the Scala 3 colors since the courses mainly use Scala 3.

The page /learn.html now contains a link to /online-courses.html:
![Screenshot 2022-01-05 at 16-31-51 Online Resources](https://user-images.githubusercontent.com/332812/148246697-14ae6179-2902-4337-b7a1-2e07fad0bfd5.png)

(also note that the layout of the page is different and now shows the table of contents on the right)

We have also added entries to the navigation menus:

![Screenshot from 2022-01-05 16-31-01](https://user-images.githubusercontent.com/332812/148246876-79bb4c10-a3df-48e6-b895-3c2363bdc6ae.png)
![Screenshot from 2022-01-05 16-31-27](https://user-images.githubusercontent.com/332812/148246877-10685620-2c6c-44f5-b728-bfc2d8009679.png)

In the /online-courses.html page, we have moved the section “Learning Paths” up to the beginning, and we have included a general video about Scala Center MOOCs (the video is not available yet) :

![Screenshot 2022-01-05 at 16-32-53 Online Courses from The Scala Center](https://user-images.githubusercontent.com/332812/148247151-51f44f9d-7c81-44b2-812d-2efab4088027.png)

---

This PR requires one more action from visitors to see the Scala Center courses. Indeed, the path used to be index.html -> learn.html. It is now index.html -> learn.html -> online-courses.html. We could address this issue by putting a link to the online courses on the index.html page.

2022-01-05 17:36 UTC, SethTisue commented
Great idea. I've often wanted to have a link to send people that just shows the Center's courses, and I never had one.

2022-01-05 17:38 UTC, SethTisue commented
While I've got your attention, have you considered a new blog post about the courses? (Sharing whatever news there is to share, yes, but primarily simply reminding everyone that they exist and are being kept up-to-date.)

2022-01-14 14:17 UTC, bishabosha requested changes
the structural changes seem fine, however as you mentioned every single item on the main docs page is no longer a button, you have to click exactly on the title in each box

2022-01-17 17:01 UTC, bishabosha requested changes
Looks good mostly, however now there is a divide: online courses appears in "First Steps" for Scala 2, but "More Detailed Information" for scala 3.

2022-01-17 17:11 UTC, julienrf commented
True, the Scala 3 front page needs more work, but I would like to do it in a separate PR.

2022-01-17 17:12 UTC, bishabosha approved these changes

2022-01-17 17:14 UTC, merged