Add Ukrainian overview
scala/docs.scala-lang pull request #2435
Opened 2022-06-17 09:13 UTC by kazanzhy

Added the main overview in Ukrainian

2022-06-18 10:23 UTC, VladKopanev commented on _data/overviews-uk.yml
> +      description: Фреймворк Scala для відображення під час виконання/компіляції.
Я би вирізняв "відображення" як views від відображень reflection, виходить просто одним словом два різних концепти в одному документі іменуються. Може reflection - віддзеркалення?

2022-06-18 10:25 UTC, VladKopanev approved these changes
LGTM, with minor comment

2022-06-18 10:51 UTC, kazanzhy commented on _data/overviews-uk.yml
> +      description: Фреймворк Scala для відображення під час виконання/компіляції.
Makes sense. Thank you

2022-06-18 11:09 UTC, CoolDalek commented on _data/overviews-uk.yml
> +      description: Фреймворк Scala для відображення під час виконання/компіляції.
Reflection - це не буквально відображення. Це філосовський термін, який означає здібність чи процес самоаналізу. В такому контексті прийнятий переклад - рефлексія.

2022-06-18 11:11 UTC, CoolDalek commented on _data/overviews-uk.yml
> +    - title: Віддзеркалення
А що робити з Mirrors? Мені здається, що тут можна було би лишити відображення з оглядом на попередній мій коментар, а відзеркалення застовувати для Mirror.

2022-06-18 11:14 UTC, VladKopanev commented on _data/overviews-uk.yml
> +    - title: Віддзеркалення
краще тоді реально рефлексія

2022-06-18 11:32 UTC, kazanzhy commented on _data/overviews-uk.yml
> +    - title: Віддзеркалення
Насправді хороше питання.
Якщо мова йде про назви класів, то я думаю, що їх не треба перекладати і використовувати `Mirror`.
Тоді reflection - рефлексія, view - відображення, Mirror - відзеркалення, WDYT?

2022-06-18 11:35 UTC, VladKopanev commented on _data/overviews-uk.yml
> +    - title: Віддзеркалення
Якщо говориш про концепти - то такий переклад норм, якщо про конкретні назви класів то треба залишити англійською, імхо

2022-06-18 11:55 UTC, CoolDalek requested changes
It's pretty good in general but requires some improvements.
Also, I must say I very much appreciate your work and efforts.
Thank you.

2022-06-18 11:55 UTC, CoolDalek commented on _data/overviews-uk.yml
> +        - title: Строки
"строка" - русизм. Українською буде "стрічка". Мені здається, вірним буде переклад "рядок", але це вже на ваш смак.

2022-06-18 11:55 UTC, CoolDalek commented on _data/overviews-uk.yml
> +      description: "Ця сторінка описує основні зміни для користувачів колекції, які переходять на Scala 2.13 і показує, як перехресно побудувати проєкти за допомогою Scala 2.11 / 2.12 і 2.13."
колекцій* - має бути множина

2022-06-18 11:55 UTC, CoolDalek commented on _data/overviews-uk.yml
> +      description: "У цьому посібнику показано, як писати операції, які можна застосувати до будь-якого типу колекції та повернути той самий тип колекції, а також як писати операції, які можна параме
Дуже перегружене речення. Читається важко.
"які можна застосувати ... та повернути ..." - неправильно сформульована частина.
Якби не поточнення про "той самий тип колекції", то здавалось би, що мова йдеться про операції.
Це додає важкості при читанні. А також дає відчуття машинного перекладу.
На жаль, більше порад конкретно тут не можу дати.

2022-06-18 11:55 UTC, CoolDalek commented on _data/overviews-uk.yml
> +        Літерал <code>s"Hello, $name"</code> є рядковим літералом, що буде додатково оброблено. Це означає, що компілятор виконує додаткову роботу над цим літералом. Оброблений рядковий літерал позна
Краще "який буде", а не "що буде".
"Інтерполяція рядка була введена в SIP-11 і яка містить усі деталі реалізації." - взагалі не розумію це речення. Як інтерполяція рядка пов'язана з деталями реалізації?..

2022-06-18 11:55 UTC, CoolDalek commented on _data/overviews-uk.yml
> +      description: "Scala 2.10 представила нову функцію під назвою неявні класи. Неявний клас — це клас, позначений неявним ключовим словом. Це ключове слово робить основний конструктор класу доступн
"неявним ключовим словом" - "ключовим словом implicit"
В даному випадку ми говоримо про конкретне ключове слово, тому його не перекладаємо.

2022-06-18 11:55 UTC, CoolDalek commented on _data/overviews-uk.yml
> +      description: "Ф'ючерси дають можливість міркувати про паралельне виконання багатьох операцій – ефективним і не блокувальним способом. Ф'ючерс — це об’єкт-заповнювач для значення, яке може ще не
Багато хто любить переклад "футури", тому це може стати спірним моментом. Я за ф'ючери, тому мені все подобається.
"блокувальний" - це призначений для блокування, а не той, що блокує. В даному випадку "не блокуючим".

2022-06-18 11:55 UTC, CoolDalek commented on _data/overviews-uk.yml
> +        - title: Configuring Parallel Collections
Пропущений переклад.

2022-06-18 12:10 UTC, Orhideous commented on _data/overviews-uk.yml
> +    - title: Quasiquotes
Квазіцитати

Той же спосіб словоутворення, що і в «квазігеоїд», «квазідержава» тощо.

2022-06-18 13:06 UTC, kazanzhy commented on _data/overviews-uk.yml
> +      description: "У цьому посібнику показано, як писати операції, які можна застосувати до будь-якого типу колекції та повернути той самий тип колекції, а також як писати операції, які можна параме
Оновив трохи.
З одного боку хочеться все написати простіше, а з іншого не хочеться вносити щось своє. 
Дякую

2022-06-18 13:12 UTC, kazanzhy commented on _data/overviews-uk.yml
> +    - title: Віддзеркалення
Дякую

2022-06-18 13:13 UTC, kazanzhy commented on _data/overviews-uk.yml
> +      description: Фреймворк Scala для відображення під час виконання/компіляції.
Дякую

2022-06-18 13:26 UTC, CoolDalek approved these changes
LGTM.

2022-06-21 07:27 UTC, merged

2022-06-21 07:27 UTC, julienrf commented
Thank you!