FAQ: revise entry on Scala versionNumberString
scala/docs.scala-lang pull request #2482
Opened 2022-07-27 18:21 UTC by SethTisue

2022-07-27 18:35 UTC, SethTisue commented
The CI failure is unrelated to this change. A different open PR has a fix.

2022-07-27 18:50 UTC, som-snytt requested changes
English is such a hard language.

2022-07-27 18:50 UTC, som-snytt commented on _overviews/FAQ/index.md
> +perhaps-unexpected Scala 2 answer:
I wonder what would be the German word for "a perhaps-unexpected Scala 2 answer".

"That's why [they] report a Scala 2 version."

2022-07-27 18:50 UTC, som-snytt commented on _overviews/FAQ/index.md
> +To aid migration, Scala 3 currently uses the Scala 2.13 library as-is.
According to all the crossword puzzle clues, "AS IS" is the answer to, "Common classified clause" or "Flea-market condition", i.e., "Won't fix."

"...library, supplemented by a few bits that are specific to Scala 3."

2022-07-28 23:57 UTC, som-snytt approved these changes
Crystal!

2022-07-28 23:59 UTC, merged

2022-07-28 23:59 UTC, SethTisue commented
(I did tweak it in response to the review feedback before merge.)