Add code tabs for scala3-book/taste-repl
scala/docs.scala-lang pull request #2487
Opened 2022-08-05 17:48 UTC by byyue

See #2481:
Scala 3 Book -> A Taste of Scala -> The REPL.

2022-08-05 19:38 UTC, bishabosha commented on _overviews/scala3-book/taste-repl.md
> +Welcome to Scala 3.1.3 (1.8.0_322, Java OpenJDK 64-Bit Server VM).
```suggestion
Welcome to Scala {{site.scala-3-version}} (1.8.0_322, Java OpenJDK 64-Bit Server VM).
```

2022-08-05 19:38 UTC, bishabosha commented on _overviews/scala3-book/taste-repl.md
> +Welcome to Scala 2.13.8 (OpenJDK 64-Bit Server VM, Java 1.8.0_342).
```suggestion
Welcome to Scala {{site.scala-version}} (OpenJDK 64-Bit Server VM, Java 1.8.0_342).
```

2022-08-05 19:39 UTC, bishabosha approved these changes
Thank you very much! The suggestions I made are just to make it more maintainable

2022-08-06 04:31 UTC, byyue commented
Thank you for the review! I have another thought: to set the Scala 3 tab as the default, at least in the _Scala 3 Book_. That's why I put it before the Scala 2 tab. 

![image](https://user-images.githubusercontent.com/46839413/183233652-715bca13-8b57-4a48-99bd-4020dadb046a.png)

@julienrf Do you consider it wise to unify this kind of format?

2022-08-09 08:39 UTC, bishabosha commented on _overviews/scala3-book/taste-repl.md
> +{% tab 'Scala 3' for=command-line %}
I hadn't noticed that the scala 3 tab came first until I saw your comment, for consistency please would you swap the tabs? :) - We will also likely rebrand the book to just the Scala Book when we have updated enough code examples

2022-08-09 08:43 UTC, bishabosha requested changes
For me personally numbers ascending left to right across the tabs makes sense, but maybe others would object - but if we chose to change the convention then that should be done globally across the site in a separate PR.

As time goes on we will likely rebrand the book to just the Scala Book when we have updated enough code examples

2022-08-09 18:10 UTC, bishabosha approved these changes

2022-08-09 18:11 UTC, merged

2022-08-09 18:11 UTC, bishabosha commented
Thanks a lot!