Update singleton-objects.md to use scala 2/3 tabs
scala/docs.scala-lang pull request #2497
Opened 2022-08-16 14:57 UTC by Sporarum

2022-08-16 16:25 UTC, julienrf requested changes
Thank you @Sporarum! I’ve noticed a couple of things that could be improved.

2022-08-16 16:25 UTC, julienrf commented on _tour/singleton-objects.md
> +  import Circle._
```suggestion
  import Circle.*
```

2022-08-16 16:25 UTC, julienrf commented on _tour/singleton-objects.md
> +import scala.math._
```suggestion
import scala.math.*
```

2022-08-16 16:25 UTC, julienrf commented on _tour/singleton-objects.md
> +import scala.math._
Or even:

```suggestion
import scala.math.pow
```

(and update the Scala 2 snippet accordingly)

2022-08-16 16:25 UTC, julienrf commented on _tour/singleton-objects.md
> +```scala mdoc
~~~suggestion
```scala
~~~

We can’t use mdoc on Scala 3 snippets.

2022-08-16 16:25 UTC, julienrf commented on _tour/singleton-objects.md
> +      case Array(a, b) => Some(new Email(a, b))
```suggestion
      case Array(a, b) => Some(Email(a, b))
```

2022-08-17 07:13 UTC, Sporarum commented
Thanks @julienrf, I added these changes !

2022-08-17 07:49 UTC, julienrf approved these changes

2022-08-17 08:00 UTC, merged