Add code tabs for _tour/compound-types
scala/docs.scala-lang pull request #2552
Opened 2022-09-22 17:29 UTC by flomebul

2022-09-23 11:35 UTC, bishabosha commented on _tour/compound-types.md
> +{% tab 'Scala 3' for=compound-types_2 %}
```suggestion
{% tab 'Scala 3' for=compound-types_3 %}
```

2022-09-27 10:31 UTC, Sporarum requested changes
Hello, thank you so much for your work on updating the pages !

I think this page is a bit particular in that aspect, as "compound type" specifically refers to `A with B`, the name for `A & B` is an [intersection type](https://docs.scala-lang.org/scala3/reference/new-types/intersection-types.html)

Since the title of page explicitly refers to the outdated term, I suggest we change it, for example to "Combining types"

The name of the file should be updated to reflect the change of name. To ensure the old address still works, please use `redirect-from` ([examples](https://github.com/jekyll/jekyll-redirect-from#usage))

2022-09-27 10:31 UTC, Sporarum commented on _tour/compound-types.md
>  The general form is: `A with B with C ... { refinement }`
I suggest we update like this:
```suggestion
Note that you can have more than two types: `A with B with C with ...`.
This means the same as thing as `(...(A with B) with C`) with ... )`
```

2022-09-27 10:31 UTC, Sporarum commented on _tour/compound-types.md
> +The general form is: `A & B & C ... { refinement }`
I suggest we update like this:
```suggestion
Note that you can have more than two types: `A & B & C & ...`. 
And `&` is associative, so parentheses can be added around any part without changing the meaning.
```

2022-09-27 12:57 UTC, Sporarum commented on _tour/intersection-types.md
> +Compound types can consist of several object types and they may have a single refinement which can be used to narrow the signature of existing object members.
This either needs to be dropped, or an example needs to be given

In all cases, we need a user-facing article on what a refinement is (there is none currently)
Especially non-structural refinement
(This is broader than this PR)

2022-09-27 12:57 UTC, Sporarum commented on _tour/intersection-types.md
> +Compound types can consist of several object types and they may have a single refinement which can be used to narrow the signature of existing object members.
Same as for Scala 2

2022-09-27 13:11 UTC, bishabosha commented
@flomebul I hope you don't mind me adding some extra commits, but I think changing the content of the article was out of the scope of "add code tabs" so I didn't want to burden that on you

2022-09-27 13:15 UTC, Sporarum approved these changes

2022-09-27 13:15 UTC, bishabosha commented
@flomebul thanks again!

2022-09-27 13:16 UTC, bishabosha approved these changes

2022-09-27 13:16 UTC, bishabosha commented
added to #2481

2022-09-27 13:26 UTC, merged