Update macros.md
scala/docs.scala-lang pull request #2603
Opened 2022-10-11 03:03 UTC by boggye

I wanted to make it clear that in the `inspect` example presented, the println call is executed at compile time.

2022-10-11 11:34 UTC, julienrf requested changes
Thank you for clarifying that! I left a minor suggestion.

Other than that, I think it might be even clearer to say where this is going to be printed (in the standard output of the compiler process, I guess?)

2022-10-11 11:34 UTC, julienrf commented on _overviews/scala3-macros/tutorial/macros.md
> +The following macro implementation prints the expression of the provided argument at compile time:
```suggestion
The following macro implementation prints the expression of the provided argument at compile-time:
```

2022-10-11 19:41 UTC, julienrf commented
It would be great if you could update the PR with the change!

2022-10-11 20:20 UTC, boggye commented
> It would be great if you could update the PR with the change!

Done.

2022-10-12 06:13 UTC, julienrf approved these changes
Thank you!

2022-10-12 06:13 UTC, merged