Add code tabs to the Scala 3 syntax rewriting
scala/docs.scala-lang pull request #2643
Opened 2022-11-19 10:44 UTC by KisaragiEffective

I'm not sure if this could help #2481, let me know (and/or submit RC review) if there are things to be fixed before proceeding. Thank you :)

2022-11-21 13:20 UTC, bishabosha commented on _overviews/scala3-migration/tooling-syntax-rewriting.md
> +{% tab 'Scala 3 Only' %}
Since this is the `build.sbt` file there is no need to surround this with tabs, unless you want to label it "sbt"

2022-11-21 13:21 UTC, bishabosha commented on _overviews/scala3-migration/tooling-syntax-rewriting.md
>  // build.sbt
```suggestion
// build.sbt, for a Scala 3 project
```

2022-11-21 13:22 UTC, bishabosha commented on _overviews/scala3-migration/tooling-syntax-rewriting.md
> +{% tabs scala-3-location_2 %}
this id was duplicated, which breaks the site rendering

```suggestion
{% tabs scala-3-location_2b %}
```

2022-11-21 13:24 UTC, bishabosha requested changes
just a few changes to make, but overall great, thanks!

2022-11-21 13:26 UTC, bishabosha commented on _overviews/scala3-migration/tooling-syntax-rewriting.md
> +{% tabs scala-3-location_2 %}
Note for self: perhaps its better to generate unique ids in the Jekyll tabs plugin, as there is not a possibility to validate uniqueness

2022-11-23 03:39 UTC, KisaragiEffective commented
fixed all in 61580cf.

2022-11-23 09:09 UTC, bishabosha approved these changes
Thanks again!

2022-11-23 09:09 UTC, merged