Add code tabs for _overviews/scala3-book/types-union.md
scala/docs.scala-lang pull request #2654
Opened 2022-12-07 20:37 UTC by jglodek

Regarding https://github.com/scala/docs.scala-lang/issues/2481
made on Warsaw Scala Spree

<img width="362" alt="image" src="https://user-images.githubusercontent.com/879088/206290182-a3f51686-bcef-404d-a13f-59a69a51074e.png">

2022-12-09 09:59 UTC, bishabosha commented on _overviews/scala3-book/types-union.md
> +{% tab 'Scala 3 Only' %}
```suggestion
{% tab 'Scala 2 and 3' %}
```

2022-12-09 09:59 UTC, bishabosha commented on _overviews/scala3-book/types-union.md
>  Other languages would require pre-planning of the class hierarchy, like the following example illustrates:
```suggestion
In other languages, such as Scala 2, you would require pre-planning of the class hierarchy, like the following example illustrates:
```

2022-12-09 10:01 UTC, bishabosha requested changes
Thanks for contributing!, just a minor point about "pre planning the class hierarchy" is meant to be a comparison to other languages, so scala 2 can be considered here

2023-04-12 14:36 UTC, julienrf commented
Hey @jglodek, thank you for opening this PR.

I went ahead and migrated the file types-union.md in #2768, so I am closing this PR.

2023-04-12 14:36 UTC, closed without merging