Use scala-cli in Getting Started page
scala/docs.scala-lang pull request #3072
Opened 2024-09-16 08:28 UTC by gkepka

2024-09-16 14:53 UTC, bishabosha requested changes
I would propose that we assume the latest scala install which should be 3.5.0 - in which case `scala-cli` should be replaced by `scala`, as described in the release notes of 3.5.0 https://scala-lang.org/blog/2024/08/22/scala-3.5.0-released.html

2024-09-16 14:53 UTC, bishabosha commented on _overviews/getting-started/index.md
> +Compiling project (Scala 3.4.2, JVM (20))
shouldn't this be 3.5.0?

2024-09-17 12:05 UTC, sjrd requested changes

2024-09-17 12:05 UTC, sjrd commented on _overviews/scala3-book/taste-hello-world.md
> +of compilation.
I don't think this is useful information for a user at this stage of their learning. Consider removing that paragraph.

2024-09-17 12:05 UTC, sjrd commented on _overviews/tutorials/scala-for-java-programmers.md
> +and executed, producing a similar output:
```suggestion
and executed, producing an output similar to:
```
("a similar output" in English refers to another output that was *previously* mentioned; there is no such thing here)

2024-09-17 16:38 UTC, bishabosha commented on _overviews/getting-started/index.md
> +Compiling project (Scala 3.5.0, JVM (20))
there's also a variable `{{site.scala-3-version}}` which can automatically update when we have a new release.

2024-10-08 11:06 UTC, bishabosha commented on _config.yml
> +scala-3-version: 3.5.1
@Gedochao updating this variable seems to be missing from the release procedure

2024-10-09 13:07 UTC, sjrd approved these changes

2024-10-09 13:07 UTC, sjrd commented on _overviews/getting-started/index.md
> +To include the toolkit libraries, use the `//> using toolkit default` directive:
```suggestion
To include the toolkit libraries, use the `//> using toolkit 0.5.0` directive:
```

2024-10-16 14:58 UTC, sjrd approved these changes

2024-10-16 14:59 UTC, merged